#!/bin/bash

source ~/.config/palette/palette.sh

val=$(/usr/lib/update-notifier/apt-check 2>&1)
normal=$(echo $val | cut -d';' -f1)
security=$(echo $val | cut -d';' -f2)

output=""
if [ $security -ne 0 ]; then
	indicator=""
	if [ $normal -ne 0 ]; then
		indicator="<sup><span foreground='#$ORANGE_FG'>+$normal</span></sup>"
	fi
	output="<span foreground='#FF0000'> </span><span font_weight='bold' foreground='#$WHITE_FG'>${security}$indicator</span>"
	#notify-send --urgency critical "$security Secutiry updates available"
elif [ $normal -ne 0 ]; then
	output="<span foreground='#ff8c00'> $normal</span>"
fi

echo "$output"

exit 0
